In [3]:
import numpy as np
import pandas as pd

from sklearn.model_selection import GridSearchCV
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier



In [4]:
import tensorflow as tf
print(tf.__version__)

2.10.1


In [5]:
import keras
keras.__version__

'2.10.0'

In [14]:
train_df=pd.read_csv('artifacts/train.csv')
test_df=pd.read_csv('artifacts/test.csv')
val_df=pd.read_csv('artifacts/validation.csv')

In [19]:
train_df

pandas.core.frame.DataFrame

In [25]:
X_train = pd.concat([train_df, test_df]).drop(columns=['label_1', 'label_X', 'label_2'], axis=1).reset_index(drop=True)
y_train = pd.concat([train_df, test_df])[['label_1', 'label_X', 'label_2']].reset_index(drop=True)

X_val = val_df.drop(columns=['label_1', 'label_X', 'label_2'], axis=1).reset_index(drop=True)
y_val = val_df[['label_1', 'label_X', 'label_2']].reset_index(drop=True)

In [26]:
X.shape

(863, 59)

In [33]:
# Define your deep learning model with increased complexity
def create_model(hidden_units=[128, 64, 32], optimizer='adam'):
    model = Sequential()
    model.add(Dense(hidden_units[0], input_shape=(X.shape[1],), activation='relu'))
    for units in hidden_units[1:]:
        model.add(Dense(units, activation='relu'))
    model.add(Dense(3, activation='softmax'))
    model.compile(loss='categorical_crossentropy', optimizer=optimizer, metrics=['accuracy'])
    return model

# Create KerasClassifier for GridSearchCV
model = KerasClassifier(build_fn=create_model, epochs=10, batch_size=32)

# Define the hyperparameters to tune
parameters = {
    'optimizer': ['adam', 'sgd'],
    'hidden_units': [(128,), (64, 32), (32, 16, 8)]
}

# Create the GridSearchCV object
grid_search = GridSearchCV(estimator=model, param_grid=parameters, cv=3)

# Perform grid search on your training data
grid_search.fit(X, y)

# Print the best hyperparameters and the corresponding accuracy
print("Best Hyperparameters: ", grid_search.best_params_)
print("Best Accuracy: ", grid_search.best_score_)


Epoch 1/10


C:\Users\Marcus Bergdahl\AppData\Local\Temp\ipykernel_1264\2565299464.py:12: DeprecationWarning: KerasClassifier is deprecated, use Sci-Keras (https://github.com/adriangb/scikeras) instead. See https://www.adriangb.com/scikeras/stable/migration.html for help migrating.
  model = KerasClassifier(build_fn=create_model, epochs=10, batch_size=32)


18/18 [==============================] - 0s 1ms/step - loss: 23.6989 - accuracy: 0.4035
Epoch 2/10
18/18 [==============================] - 0s 1ms/step - loss: 9.5340 - accuracy: 0.4017
Epoch 3/10
18/18 [==============================] - 0s 1ms/step - loss: 6.7368 - accuracy: 0.4104
Epoch 4/10
18/18 [==============================] - 0s 1ms/step - loss: 4.9384 - accuracy: 0.4243
Epoch 5/10
18/18 [==============================] - 0s 1ms/step - loss: 5.1138 - accuracy: 0.4278
Epoch 6/10
18/18 [==============================] - 0s 1ms/step - loss: 3.7135 - accuracy: 0.4696
Epoch 7/10
18/18 [==============================] - 0s 1ms/step - loss: 3.2144 - accuracy: 0.4452
Epoch 8/10
18/18 [==============================] - 0s 1ms/step - loss: 2.7645 - accuracy: 0.5148
Epoch 9/10
18/18 [==============================] - 0s 1ms/step - loss: 2.8681 - accuracy: 0.4870
Epoch 10/10
9/9 [==============================] - 0s 2ms/step - loss: 5.2097 - accuracy: 0.4479
Epoch 1/10
18/18 [=============

In [35]:
# Evaluate the model on the validation set
best_model = grid_search.best_estimator_
result = best_model.predict_proba(X_val)
print("Validation Predictions:")
print(result)

7/7 [==============================] - 0s 1ms/step
Validation Predictions:
[[0.41772482 0.24013184 0.34214336]
 [0.41772482 0.24013184 0.34214336]
 [0.4042713  0.25156066 0.344168  ]
 [0.41772482 0.24013184 0.34214336]
 [0.41772482 0.24013184 0.34214336]
 [0.41772482 0.24013184 0.34214336]
 [0.41772482 0.24013184 0.34214336]
 [0.443106   0.2955525  0.26134157]
 [0.35482514 0.30540445 0.33977035]
 [0.41772482 0.24013184 0.34214336]
 [0.41772482 0.24013184 0.34214336]
 [0.41772482 0.24013184 0.34214336]
 [0.41772482 0.24013184 0.34214336]
 [0.41772482 0.24013184 0.34214336]
 [0.41772482 0.24013184 0.34214336]
 [0.41772482 0.24013184 0.34214336]
 [0.41772482 0.24013184 0.34214336]
 [0.41772482 0.24013184 0.34214336]
 [0.41772482 0.24013184 0.34214336]
 [0.41772482 0.24013184 0.34214336]
 [0.2223521  0.26960424 0.50804365]
 [0.41772482 0.24013184 0.34214336]
 [0.41772482 0.24013184 0.34214336]
 [0.41772482 0.24013184 0.34214336]
 [0.41772482 0.24013184 0.34214336]
 [0.41772482 0.24013184 0